bot_user_oauth_token: ""
default_channel_id: ""
default_headers:
  Content-Type: "application/x-www-form-urlencoded,application/json"
post_message_url: "https://slack.com/api/chat.postMessage"
get_list_of_channels_url: "https://slack.com/api/conversations.list"
get_messages_url: "https://slack.com/api/conversations.history"