access_token: ""
access_token_secret: ""
api_key: ""
api_key_secret: ""
personal_username: ""
tw_users:
  python:
    - PythonWeekly
    - realpython
    - fullstackpython
  javascript:
    - JavaScriptDaily
  "c#":
    - CSharpStack
  "c++":
    - lefticus